version: "3.8"

services:
  postgres:
    image: postgres:17 # Altere para a versão 17 do PostgreSQL
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  my-python-app:
    build: .
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    command: >
      bash -c "sleep 10 && python /app/main.py"

volumes:
  postgres_data:
